// <auto-generated />
namespace MyCV_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mig0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig0));
        
        string IMigrationMetadata.Id
        {
            get { return "201611252120001_mig0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
