// <auto-generated />
namespace Final_CV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig00));
        
        string IMigrationMetadata.Id
        {
            get { return "201611272028251_mig00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
